# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

# Disable line break in prompt
[line_break]
disabled = true

# Disable previous command duration in prompt
[cmd_duration]
disabled = true
